<div class="visit-showroom">
    <h3>{{trans('web.footer.visit_our_showroom.title')}}</h3>
    <div class="container">
        <div class="row clearfix">
            <div class="col-sm-7 col-md-8">
                <div class="dourado_video">
                    <section class="video-section bg-snow pt-50 mb-50 rpt-50 pb-50 rpb-60">
                        <div class="container">
                            <div class="row">
                                @if(count($links))
                                    <div id="player" class="col-lg-12 mt-5">
                                        <div class="player">
                                            <div class="player__video">
                                                <!-- Current video is for reference only. It will be generated by JavaScript code. -->
                                                <iframe id="current-video" class="current-video" width="560" height="315"
                                                        src="https://www.youtube.com/embed/{{$links->first()->link}}" frameborder="0"
                                                        allow="autoplay; encrypted-media" allowfullscreen></iframe>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="gallery" class="col-lg-12">
                                        <div class="gallery"></div>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </section>
                </div>
            </div>
            <div class="col-sm-5 col-md-4">
                <div class="get-in-touch-box">
                    <h4 class="aos-init aos-animate">{{trans('web.footer.visit_our_showroom.get_in_touch_title')}}</h4>
                    <div class="showroom_msg text-white mb-2 p-2 hidden"></div>
                    <form id="visitForm" method="post">
                        <div data-aos="fade-up" data-aos-duration="1000" class="aos-init aos-animate">
                            <div class="form-group">
                                <input maxlength="30" class="form-control" name="full_name" id="full_name" type="text"
                                       placeholder="{{trans('web.footer.visit_our_showroom.form.full_name_placeholder')}}"
                                       autocomplete="off" required>
                            </div>
                            <div class="form-group">
                                <input class="form-control" maxlength="15"
                                       name="mobile_number"
                                       id="mobile_number" type="text"
                                       placeholder="{{trans('web.footer.visit_our_showroom.form.mobile_number_placeholder')}}"
                                       autocomplete="off" required>
                            </div>
                            <div class="form-group">
                                <input name="date" id="date"
                                       class="form-control datepickers prefferedDate hasDatepicker" type="date"
                                       placeholder="{{trans('web.footer.visit_our_showroom.form.preferred_date_placeholder')}}"
                                       autocomplete="off" required>
                            </div>
                            <div class="form-group">
                                <input name="time" id="time"
                                       class="form-control datepickers prefferedTime hasDatepicker" type="time"
                                       placeholder="{{trans('web.footer.visit_our_showroom.form.preferred_time_placeholder')}}"
                                       autocomplete="off" required>
                            </div>
                            <div class="form-group">
                                <select name="interested" class="form-select" id="interested" required>
                                    <option>{{trans('web.footer.visit_our_showroom.im_interested_in')}}</option>
                                    <option value="Car Viewing">{{trans('web.footer.visit_our_showroom.car_viewing')}}</option>
                                    <option value="Sell My Car">{{trans('web.footer.visit_our_showroom.sell_my_car')}}</option>
                                </select>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary">{{trans('web.footer.visit_our_showroom.form.preferred_time_placeholder')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    const links = JSON.parse(`@json($links)`);
    let arrVideos = [];
    const ytVideoPrefix = `https://www.youtube.com/embed/`
    const ytImagePathPrefix = `https://i.ytimg.com/vi/`
    const ytImagePathSufix = `/maxresdefault.jpg`

    for (var i = 0; i < links.length; i++) {
        arrVideos.push({data: links[i].link});
    }
    let currentVideo = document.getElementById('current-video')
    currentVideo.src = `${ytVideoPrefix}${arrVideos[0].data}`


    let gallery = document.querySelector('.gallery')
    gallery.innerHTML = ``

    for (let i = 0; i < arrVideos.length; i++) {
        gallery.innerHTML += `
            <div class="gallery__item filtered"
            style="background-image: url(${ytImagePathPrefix}${arrVideos[i].data}${ytImagePathSufix})"
            data="${arrVideos[i].data}">
            </div>`
    }

    gallery.addEventListener('click', (e) => {
        // When click on .gallery__item element
        if (e.target.classList.contains('gallery__item')) {
            currentVideo.src = `${ytVideoPrefix}${e.target.getAttribute('data')}`
        }
        // When click on .gallery__item__img element
        if (e.target.classList.contains('gallery__item__img')) {
            let data = e.target.src
            data = data.replace(ytImagePathPrefix, '')
            data = data.replace(ytImagePathSufix, '')
            currentVideo.src = `${ytVideoPrefix}${data}`
            console.log(currentVideo.src)
        }
        // When click on .gallery__item__span element
        if (e.target.classList.contains('gallery__item__span')) {
            console.log(e.target.innerText)
            for (let i = 0; i < arrVideos.length; i++) {
                if (arrVideos[i].name === e.target.innerText) {
                    currentVideo.src = `${ytVideoPrefix}${arrVideos[i].data}`
                }
            }
        }
    });
</script>
